chaeuda-TEAM/oz-main-be-06-team2

django/a_apis/models/products.py

fix : models import update, add.

5 feat 매물정보

---

django/a_apis/api/api.py
django/a_apis/api/products.py
django/a_apis/models/__init__.py
django/a_apis/models/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py

products.py 생성 ( api, schema, service)

6 feat map api

---

django/a_apis/models/products.py
django/a_core/urls.py

ProductContents 모델 __str__ 메서드 TypeError 수정

51 fix product content

---

.github/workflows/dev-check.yml
.gitignore

수정파일:
- `.github/workflows/dev-check.yml`
변경내용:
- 환경 변수 추가: `DEV_AWS_RDS_NAME`, `DEV_AWS_RDS_USER`, `DEV_AWS_RDS_PASSWORD`, `DEV_AWS_RDS_HOST`, `DEV_AWS_RDS_PORT`
- 마이그레이션 생성과 실행 시 `--plan` 옵션 추가 및 설정 파일을 `a_core.settings.dev-aws`로 변경
특이사항:
- `.gitignore` 파일에 변경 내용 없음

feat: Add migration plan check workflow for dev branch(#68)

---

README.md

Chore:test for merge

---

.github/workflows/dev-check.yml

수정파일: `.github/workflows/dev-check.yml`
수정내용:
- `poetry run python manage.py makemigrations --dry-run --settings=a_core.settings.dev-aws` 명령어 제거
- `poetry run python manage.py migrate --check --settings=a_core.settings.dev-aws` 명령어 제거
- `poetry run python manage.py migrate --settings=a_core.settings.dev-aws` 명령어 추가
- `Check runserver` 작업 추가
특이사항: 없음

68 feat create test code for django migrate

---

django/a_apis/admin.py
django/a_apis/models/products.py

- `django/a_apis/admin.py`
- `django/a_apis/models/products.py`
- `django/a_apis/admin.py`:
- `ProductDetailAdmin`의 `list_display` 항목에서 `user`를 `get_user_info`로 변경
- `django/a_apis/models/products.py`:
- `ProductAddress`, `ProductVideo`, `ProductDetail`, `ProductImg` 클래스의 `id` 필드를 `AutoField`에서 `BigAutoField`로 변경
- `ProductDetail`의 `user` 필드를 `user_no`로 변경하고, `db_column` 속성을 추가
- `ProductDetail` 클래스에 `get_user_info` 메서드 추가
- `ProductImg` 클래스의 `verbose_name` 속성 수정
- `ProductDetailAdmin` 클래스에서 `get_user_info` 메서드를 이용해 사용자 정보를 표시하도록 변경되었습니다.
- 모델 클래스의 `id` 필드를 `BigAutoField`로 변경하여 더 큰 범위의 ID를 지원하도록 수정되었습니다.
- `ProductDetail` 모델에서 `user` 필드가 `user_no`로 변경되었으며, 이를 통해 데이터베이스에서의 컬럼명이 명확하게 지정되었습니다.

fix: Update model fields and admin configuration(#93)

---

.github/workflows/pr-check.yml

- Add workflow to check PR source branch
- Only allow PRs from dev branch to main
- Block PRs from other branches
- Improve branch protection strategy

99 feat setting pr from dev to main

---

.github/workflows/pr-check.yml
django/a_apis/models/products.py

- `.github/workflows/pr-check.yml`
- 새 파일 추가:
```yaml
name: Restrict Pull Requests to main
on:
pull_request:
branches:
- main
jobs:
restrict-pr:
runs-on: ubuntu-latest
steps:
- name: Check if PR source is dev
run: |
if [[ "${{ github.head_ref }}" != "dev" ]]; then
echo "❌ Pull requests to 'main' must come from 'dev' branch only."
exit 1
```
- 이 워크플로우는 'main' 브랜치로의 Pull Request가 'dev' 브랜치에서만 생성될 수 있도록 제한합니다.

Add GitHub Action to restrict PRs to main branch

---

django/a_apis/api/products.py
django/a_apis/schema/products.py

- 매물 상세 API의 Schema에 `description` 추가

92 chore product schema

---

django/a_core/settings/base.py
poetry.lock
pyproject.toml

- `poetry.lock`
- `pyproject.toml`
- `django/a_core/settings/base.py`
- `poetry.lock`: 변경 사항 없음.
- `pyproject.toml`: `django-cleanup` 패키지를 추가했습니다.
```diff
+ django-cleanup = "^9.0.0"
```
- `django/a_core/settings/base.py`: `INSTALLED_APPS`에 `django_cleanup.apps.CleanupConfig` 추가
```diff
+ "django_cleanup.apps.CleanupConfig",
```
- `django-cleanup` 패키지를 사용해 파일 삭제를 자동화합니다.

feat: Add django-cleanup for automatic file deletion

---

django/a_apis/api/products.py
django/a_apis/service/users.py

- `django/a_apis/service/users.py`
- `django/a_apis/api/products.py`:
- `ProductDetail` 모델의 임포트 위치 수정.
- `public_router` 추가.
- `django/a_apis/service/users.py`:
- 비밀번호 복잡성 검사에서 사용자 객체가 존재하지 않을 경우를 처리하도록 조건문 수정.
- 회원가입 시 소셜 로그인 사용자 여부를 적절히 확인하도록 수정.
- `products.py` 파일에서 `ProductDetail` 모델의 임포트 위치가 변경되었습니다.
- `users.py` 파일에서 비밀번호 복잡성 검사를 위한 조건문이 수정되어, 사용자가 존재하지 않거나 소셜 로그인 사용자가 아닌 경우만 검사를 수행합니다.
- 회원가입 시, 소셜 로그인 사용자의 재등록 시에도 적절히 처리가 이루어지도록 개선되었습니다.

82 fix social withdraw

---

django/a_apis/tests/test_users.py

수정파일: `django/a_apis/tests/test_users.py`
수정내용:
- 이메일 인증 요청 테스트가 추가됨
- 이메일 인증 테스트가 추가됨
- 정상적인 회원가입 테스트가 추가됨
- 불필요한 테스트 코드가 제거됨
- `override_settings` 데코레이터 추가
- `mail` 모듈을 사용하여 이메일 발송 여부 및 내용을 확인하는 코드 추가
특이사항:
- 테스트 코드가 기존 `unittest` 방식에서 `pytest` 스타일로 전환됨
- 파일 구조가 변경되고, 기존의 불필요한 코드가 삭제됨
이 변경 사항들은 이메일 인증 절차와 관련된 테스트 코드를 강화하고, 전체 테스트 구조를 개선하기 위한 것으로 보입니다.

114 test signup by email

---

django/a_apis/auth/bearer.py

수정파일: `django/a_apis/auth/bearer.py`
수정내용:
- `from rest_framework_simplejwt.exceptions import TokenError` 제거
- `from django.contrib.auth import get_user_model` 추가
- `User = get_user_model()` 추가
- `AccessToken(token)` → `access_token = AccessToken(token)`
- `user = User.objects.get(id=access_token["user_id"])` 추가
- `request.user = user` 추가
- `except TokenError:` → `except Exception:`
특이사항:
- 유저 인증이 추가되어 request 객체에서 사용자를 쉽게 접근할 수 있게 했습니다.
- 예외 처리에서 `TokenError` 대신 일반 `Exception`을 사용하도록 변경했습니다.

122 fix user auth

---

django/a_apis/auth/bearer.py
django/a_apis/tests/test_users.py

수정파일: `django/a_apis/auth/bearer.py`
수정내용:
- `from rest_framework_simplejwt.exceptions import TokenError` 제거
- `from django.contrib.auth import get_user_model` 추가
- `User = get_user_model()` 추가
- `AccessToken(token)` → `access_token = AccessToken(token)`
- `user = User.objects.get(id=access_token["user_id"])` 추가
- `request.user = user` 추가
- `except TokenError:` → `except Exception:`
특이사항:
- 유저 인증이 추가되어 request 객체에서 사용자를 쉽게 접근할 수 있게 했습니다.
- 예외 처리에서 `TokenError` 대신 일반 `Exception`을 사용하도록 변경했습니다.

Dev to main - auth/bearer

---

django/a_apis/api/products.py
django/a_apis/middleware.py
django/a_apis/models/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py
django/a_core/settings/base.py
django/a_core/settings/s3-development.py

- `django/a_apis/middleware.py`: 새로운 파일 추가
- `django/a_apis/models/products.py`
- `django/a_apis/schema/products.py`
- `django/a_apis/service/products.py`
- `django/a_core/settings/base.py`
- 새로운 파일로 추가됨.
```diff
+ pro_rooms = models.IntegerField(verbose_name="방 갯수")
+ pro_bathrooms = models.IntegerField(verbose_name="욕실 갯수")
+ pro_construction_year = models.IntegerField(verbose_name="건축연도")
```
```diff
+ from typing import Optional, Union
+ management_cost: Optional[int] = Field(default=None, description="관리비")
+ sale: Optional[bool] = Field(default=True, description="판매여부")
+ pro_rooms: int = Field(..., description="방 갯수")
+ pro_bathrooms: int = Field(..., description="욕실 갯수")
+ pro_construction_year: int = Field(..., description="건축연도")
- …
```

113 feat edit product api

---

django/a_apis/api/products.py
django/a_apis/api/users.py
django/a_apis/schema/users.py
django/a_apis/service/email.py
django/a_apis/service/users.py

수정파일:
- `django/a_apis/api/users.py`
- `django/a_apis/schema/users.py`
- `django/a_apis/service/email.py`
- `django/a_apis/service/users.py`
수정내용:
- `django/a_apis/api/products.py`: 이동된 `from a_apis.models import ProductDetail` 문.
- `django/a_apis/api/users.py`: 회원 정보 수정 엔드포인트 추가.
- `django/a_apis/schema/users.py`: `UpdateProfileSchema` 클래스 추가.
- `django/a_apis/service/email.py`: `verify_email` 함수에서 `Response` 객체 사용으로 변경.
- `django/a_apis/service/users.py`: 모든 응답을 `Response` 객체로 변경, `update_user_profile` 메서드 추가.
특이사항:
- 기존 `dict` 반환 방식에서 `Response` 객체 반환 방식으로 변경.
- `update_user_profile` 메서드가 추가되어 회원 정보 수정 기능이 추가됨.

Dev - feat: Implement consistent API response format with status codes(#121 #131)

---

django/a_apis/schema/users.py
django/a_apis/service/users.py

수정파일:
- `django/a_apis/schema/users.py`
- `django/a_apis/service/users.py`
수정내용:
- `schema/users.py`: `UserResponseSchema` 클래스에 `phone_number` 필드 추가.
- `service/users.py`: `login_user`와 `get_user` 함수에서 `phone_number`를 응답에 포함하도록 수정.
특이사항:
- 주요 변경 사항은 사용자 정보 응답에 전화번호를 포함시키는 기능 추가입니다.

feat: Add phone number to user response schema and service(#138)

---

django/a_apis/schema/users.py
django/a_apis/service/users.py

수정파일:
- `django/a_apis/schema/users.py`
- `django/a_apis/service/users.py`
수정내용:
- `schema/users.py`: `UserResponseSchema` 클래스에 `is_active` 필드 추가.
- `service/users.py`: `login_user`, `get_user`, `signup` 함수에서 `is_active`를 응답에 포함하도록 수정.
특이사항:
- 주요 변경 사항은 사용자 정보 응답에 활성 상태를 나타내는 `is_active` 필드를 추가한 것입니다.

142 fix display is active when me

---

django/a_apis/api/products.py
django/a_apis/models/__init__.py
django/a_apis/models/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py
django/a_core/settings/base.py

수정 파일 목록:
- `django/a_apis/models/__init__.py`
- `django/a_apis/models/products.py`
- `django/a_apis/schema/products.py`
- `django/a_apis/service/products.py`
- `django/a_core/settings/base.py`
수정 내용:
- `JsonResponse`를 `Response`로 변경
- `toggle_like_product` API 추가
- `django/a_apis/models/__init__.py`
- `ProductLikes` import 추가
- `django/a_apis/models/products.py`
- `ProductDetail` 모델에 `likes` 필드 추가
- `ProductLikes` 중간 테이블 모델 추가
- `django/a_apis/schema/products.py`
- `ProductLikeResponseSchema` 추가
- `django/a_apis/service/products.py`
- `ProductLikes` import 추가
- `JsonResponse`를 `Response`로 변경
- `toggle_like_product` 메소드 추가
- `django/a_core/settings/base.py`
- `LANGUAGE_CODE`를 `ko-kr`로 변경
- `TIME_ZONE`을 `Asia/Seoul`로 변경
- …

141 feat likes products

---

django/a_apis/api/products.py
django/a_apis/service/email.py

- `django/a_apis/service/email.py`
- `django/a_apis/api/products.py`:
- `ProductDetail` import 제거 및 재추가 위치 변경
- `django/a_apis/service/email.py`:
- 이메일 검증 추가 및 예외 처리 개선
- `ProductDetail` import 위치가 변경되었습니다.
- 이메일 서비스에 이메일 형식 검증 및 예외 처리가 추가되었습니다.

119 fix email formatting

---

django/a_apis/api/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py

- **파일**: `django/a_apis/service/products.py`
- **`django/a_apis/service/products.py`**:
- `mylist_like_products` 함수에 찜한 매물이 없는 경우를 처리하는 로직 추가.
- 찜한 매물이 없을 경우 정상 응답을 반환하도록 수정.
- `mylist_like_products` 함수에서 찜한 매물이 없는 경우에도 성공 응답을 반환하도록 개선.

[Merge] Dev -> Main

---

django/a_apis/api/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py

- `django/a_apis/schema/products.py`
- `django/a_apis/service/products.py`
1. **`schema/products.py` 파일:**
- `UserLikedProductsResponseSchema` 클래스에 이어 새로운 `ProductDetailResponseSchema` 및 `UserProductsResponseSchema` 클래스를 추가하여 매물 상세 정보와 등록 매물 목록을 위한 스키마를 정의.
2. **`api/products.py` 파일:**
- `UserProductsResponseSchema`를 임포트.
- 새로운 API 엔드포인트 `/products-mylist`를 추가하여 사용자가 등록한 매물 목록을 조회하는 기능 구현.
- 새로운 매물 조회 API 기능이 추가되었으며, 사용자가 등록한 매물 목록을 조회할 수 있는 엔드포인트 추가.
- 사용자가 등록한 매물 목록 조회 시, 매물이 없을 경우에도 정상 응답을 반환하도록 처리.
- API 오류 발생 시 적절한 예외 처리를 통해 에러 메시지를 반환.
- 현재 스키마 정의한게 너무 많아서.. 추후에 매물 관련 스키마를 하나로 정의하여 통일 시킬 예정 @-@..

Feat : 나의매물조회 API (#152)

---

docker-compose.yml

chore: Update resource limits in docker-compose(#80)

---

django/Dockerfile
docker-compose.yml

- Reduced CPU limit to 0.50 and increased memory limits in docker-compose.yml for better resource management.
- Updated Gunicorn command in Dockerfile to use 2 workers and added additional parameters for improved performance and connection handling.

chore: Optimize resource allocation and update Gunicorn 

---

django/a_apis/api/products.py
django/a_core/settings/dev-aws.py
django/a_core/settings/product_asgi.py

- Changed environment variable names in dev-aws.py for consistency with AWS naming conventions.
- Added socket keepalive settings and connection pool options in product_asgi.py to improve connection stability and performance.
- Cleaned up redundant import in products.py for better code clarity.

chore: Update database settings and enhance socket configurations

---

django/a_core/settings/product_asgi.py

- Removed redundant CONNECTION_POOL_KWARGS setting for cleaner configuration.
- Updated Redis host configuration to use a formatted string for improved clarity and consistency.

chore: Refactor Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed Redis connection protocol from 'rediss' to 'redis' for standardization.
- Simplified host configuration by using a tuple instead of a formatted string.
- Removed SSL-related settings from CHANNEL_LAYERS for a cleaner configuration.

chore: Update Redis connection settings in product_asgi.py

---

django/a_core/asgi.py

- Changed the DJANGO_SETTINGS_MODULE environment variable from 'dev-aws-aec' to 'product_asgi' for deployment readiness.

chore: Update ASGI settings to use production configuration

---

django/a_core/settings/product_asgi.py

- Added Redis client kwargs for cluster support and response decoding.
- Updated CHANNEL_LAYERS configuration to use a formatted Redis connection string.
- Introduced a session cookie age setting for improved session management.
- Set a prefix for ASGI channels to avoid key collisions.

feat: Enhance Redis and session settings in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Updated CACHES LOCATION to a string format for clarity.
- Changed CLIENT_CLASS to use HerdClient for improved performance.
- Enhanced CONNECTION_POOL_KWARGS with max_connections and retry_on_timeout settings.
- Modified CHANNEL_LAYERS hosts configuration to a tuple format for better readability.
- Removed unnecessary settings to streamline Redis integration.

refactor: Simplify Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Removed redundant socket timeout settings from CACHES configuration.
- Added HSTS settings to enhance security for production environment.
- Streamlined Redis configuration by eliminating unnecessary cluster settings.

refactor: Update Redis and security settings in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed CHANNEL_LAYERS hosts to use a formatted Redis connection string for clarity.
- Enabled cluster mode and added symmetric encryption keys for enhanced security.

feat: Update Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Reformatted CHANNEL_LAYERS hosts to improve readability.
- Removed the cluster_mode setting for a simplified Redis setup.

refactor: Clean up Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed CLIENT_CLASS from HerdClient to DefaultClient for compatibility.
- Reformatted CHANNEL_LAYERS hosts for improved readability.

refactor: Update Redis client configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Updated CLIENT_CLASS to DefaultClient for compatibility with Redis cluster mode.
- Added REDIS_CLIENT_CLASS and CONNECTION_POOL_CLASS for improved cluster support.
- Introduced socket connection and timeout settings for better connection management.

refactor: Enhance Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Simplified CACHES 'LOCATION' format from a list to a string for clarity.
- Updated CLIENT_CLASS from HerdClient to DefaultClient for improved compatibility.
- Reorganized REDIS_CLUSTER_OPTIONS to enhance readability and maintainability.
- Reformatted CHANNEL_LAYERS hosts to use a dictionary structure for better configuration.

refactor: Streamline Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed CLIENT_CLASS from DefaultClient to HerdClient for improved performance in cluster environments.
- Modified REDIS_CLUSTER_OPTIONS to use 'startup_nodes' for better cluster initialization.
- Added comments for clarity on endpoint correctness and configuration options.

refactor: Update Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

어드민페이지 들어가짐..
- Streamlined CACHES 'LOCATION' format for clarity.
- Updated CLIENT_CLASS to 'HerdClient' for improved performance.
- Added 'MAX_CONNECTIONS' and 'socket_keepalive' options for better connection management.
- Removed unnecessary REDIS_CLUSTER_OPTIONS for a cleaner configuration.

🍭 refactor: Simplify and enhance Redis configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed WebSocket URL from 'wss' to 'ws' for compatibility.
- Updated CACHES configuration to use 'DefaultClient' and 'RedisCluster' for improved performance and cluster support.
- Adjusted connection pool settings, reducing 'max_connections' to 50 and adding 'socket_timeout' for better resource management.
- Enhanced comments for clarity on cache and session settings.

refactor: Update Redis and WebSocket configuration in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Updated CACHES configuration to use 'HerdClient' for improved performance.
- Enhanced connection options, increasing 'MAX_CONNECTIONS' to 100 and adding 'RETRY_ON_TIMEOUT' for reliability.
- Simplified comments for clarity on Redis cluster usage and connection settings.
- Adjusted CHANNEL_LAYERS to reflect single endpoint usage while noting limitations with cluster mode.
- Improved session and AWS S3 settings for better integration and performance.

refactor: Revise Redis and caching settings in product_asgi.py

---

django/a_core/settings/product_asgi.py

- Changed CACHES configuration to use 'DefaultClient' and 'redis.cluster.RedisCluster' for improved compatibility with Redis clusters.
- Adjusted connection pool settings, reducing 'max_connections' to 50 and adding 'decode_responses' for better resource management.
- Updated session management to use file-based storage instead of cache, specifying SESSION_FILE_PATH for session data.
- Enhanced CHANNEL_LAYERS configuration for clarity and consistency with Redis connection settings.

refactor: Update Redis and session settings in product_asgi.py

---

django/Dockerfile
docker-compose.yml

- Changed DJANGO_SETTINGS_MODULE to 'a_core.settings.product_asgi' for ASGI compatibility.
- Added installation of 'uvicorn' for ASGI server support.
- Updated migration and static file collection commands to use the new settings module.
- Modified CMD instruction to run the application with 'uvicorn' worker for improved performance.

refactor: Update Docker configuration for ASGI support

---

django/a_chat/consumers.py
django/a_core/dev-asgi.py

Enhance ChatConsumer to retrieve previous chat messages and user details. Added a new ASGI configuration file for improved websocket handling and database connection management.

Fix: previous message for chat (#260)

---

django/a_apis/models/products.py
django/a_common/models.py

- **수정 목록**
- `django/a_apis/models/products.py`
- `django/a_common/models.py`
- **수정 내용**
- `django/a_apis/models/products.py`
- `ProductAddress` 모델에 `is_deleted` 필드 추가
- `ProductVideo` 모델에 `is_deleted` 필드 추가
- `ProductDetail` 모델에 `is_deleted` 필드 추가
- `ProductImg` 모델에 `is_deleted` 필드 추가
- `ProductLikes` 모델에 `is_deleted` 필드 추가
- `django/a_common/models.py`
- `CommonModel`에서 `is_deleted` 필드 제거
- **특이사항**
- `is_deleted` 필드를 각 개별 모델에 추가하여 soft delete 기능을 구현
- `CommonModel`에서 `is_deleted` 필드 제거로 인해 상속받는 모델들이 독립적으로 삭제 여부를 관리하도록 변경

269 fix is deleted field

---

django/a_apis/models/products.py
django/a_apis/schema/products.py
django/a_apis/service/products.py

- `ProductLikes` 모델에 `is_liked` 필드 추가
- `ProductLikeResponseSchema`에서 `created_at` 필드 제거
- `ProductDeleteResponseSchema`에서 필드 선언 방식 변경
- `create_product` 함수에서 불필요한 `response_data` 제거 및 `is_liked` 필드 초기화
- `update_product` 함수에서 `ProductLikes` 객체 존재 여부에 따른 `is_liked` 필드 업데이트 로직 추가
- `toggle_like_product` 함수에서 `ProductLikes` 객체 생성 및 `is_liked` 상태 토글
- `mylist_like_products` 함수에서 `is_liked=True` 조건 추가
- `mylist_products` 함수에서 `ProductLikes` 테이블을 사용한 `is_liked` 상태 확인 로직 수정
- `get_product_detail` 함수에서 `is_liked` 상태 확인 로직 수정
- `get_nearby_products` 함수에서 `is_liked` 상태 확인 로직 수정
- 여러 곳에서 `is_liked` 상태 확인 로직을 수정함.
- 불필요한 필드나 데이터 제거.
- `ProductLikes` 모델에 새로운 필드 추가로 기능 확장.
- `ProductLikes` 모델에 `is_liked` 필드가 추가되면서 관련 로직들이 수정됨.
- `toggle_like_product` 함수에서 `ProductLikes` 객체가 없으면 생성하고, 있으면 상태를 토글하는 로직이 …

279 chore productlikes model

---

django/a_apis/api/users.py
django/a_apis/service/users.py

- Removed the `data` parameter from the `withdraw` function in `users.py`, streamlining the endpoint.
- Updated the `withdraw_user` method in `UserService` to include user activation status in the response, enhancing clarity on user status during withdrawal.

Refactor: Simplify user withdrawal process(#282)

---

django/a_apis/api/products.py
django/a_apis/auth/decorators.py

- `django/a_apis/api/products.py` 파일 수정
- `django/a_apis/auth/decorators.py` 파일 추가
- **`django/a_apis/api/products.py`**
- `optional_auth` 데코레이터 추가
- `get_product_detail` 및 `get_nearby_products` 메서드에 `optional_auth` 데코레이터 추가
- **`django/a_apis/auth/decorators.py`**
- 새로운 파일로 `optional_auth` 데코레이터 구현
- 사용자 인증 토큰을 검증하고, 유효한 경우 `request.user`에 사용자 정보를 설정
- public_router 에서 로그인 유저도 비로그인으로 처리된 문제 해결
- 모든 변경사항은 인증 및 사용자 참조 관련
- 새로운 데코레이터 파일 추가 및 기존 API 메서드에 적용
- 사용자 인증 로직을 새로운 데코레이터로 분리

Fix : product likes 부분 개선(#281)

---

django/a_apis/schema/products.py
django/a_apis/service/products.py

- `django/a_apis/service/products.py`
- `django/a_apis/schema/products.py`
- `django/a_apis/service/products.py` 파일:
- `get_product_detail` 함수에서 `UserDetailSchema`의 `id` 필드를 `email` 필드로 변경.
- `django/a_apis/schema/products.py` 파일:
- `UserDetailSchema` 클래스에서 `id` 필드를 `email` 필드로 변경.
- 사용자 정보를 나타내는 스키마에서 `id` 대신 `email` 으로 변경.

Chore : 매물상세조회 api 응답데이터 수정(#290)
